/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRestoran.waiter;
import javax.swing.table.DefaultTableModel;

import AplikasiRestoran.MainFrame;
import AplikasiRestoran.auth.User;
import Models.Menu;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author idaba
 */
public class WaiterPanel extends javax.swing.JInternalFrame {
    private Statement st;
    private ResultSet rs;
    private DefaultTableModel tabModel;
    private DefaultTableModel tabModelPesanan;
    private DefaultTableModel tabModelKeranjang;
    private Connection cn = Koneksi.Koneksi.koneksiDB();

    private LocalDateTime now = LocalDateTime.now();
    
    private String idTransaksi;
    private String idTransaksiPesanan;
    private int stok;
    /**
     * Creates new form WaiterPanel
     */
    public WaiterPanel(User user) {
        initComponents();
        name.setText(user.getName());
        roles.setText(user.getRoles());
        
        judul();
        judulPesanan();
        judulKeranjang();
        tampilData("");
        tampilDataPesanan("");
        tampilDataMeja();
        tampilDataKeranjang();
        
        menu_id.setEnabled(false);
        harga.setEnabled(false);
        nama_menu.setEnabled(false);
        jumlah.setEnabled(false);
        
        tableMenu.setEnabled(false);
        tableKeranjang.setEnabled(false);
        btnBatal.setEnabled(false);
        btnTambah.setEnabled(false);
        btnKonfirmasi.setEnabled(false);
        btnBatalKeranjang.setEnabled(false);
        btnKonfirmasiPesanan.setEnabled(false);
        
//        System.out.println(dtf);
        System.out.println(now);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roles = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenu = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKeranjang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        meja = new javax.swing.JComboBox<>();
        jumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama_menu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        menu_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        btnKonfirmasi = new javax.swing.JButton();
        btnBatalKeranjang = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePesanan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Nama1 = new javax.swing.JLabel();
        Nama2 = new javax.swing.JLabel();
        btnKonfirmasiPesanan = new javax.swing.JButton();
        detailNama = new javax.swing.JLabel();
        detailMeja = new javax.swing.JLabel();
        listDetailPesanan = new java.awt.List();

        roles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roles.setText("-");

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setText("-");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setText("Daftar Menu");

        tableMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMenu);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Keranjang");

        tableKeranjang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableKeranjang);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nama");

        nama.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Meja");

        meja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        meja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejaActionPerformed(evt);
            }
        });

        jumlah.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Jumlah");

        nama_menu.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Menu");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("ID");

        menu_id.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Harga");

        harga.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnKonfirmasi.setText("Konfirmasi");
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        btnBatalKeranjang.setText("Batal");
        btnBatalKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalKeranjangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(meja, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel5))
                                .addGap(99, 99, 99)
                                .addComponent(jLabel10))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(546, 546, 546))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menu_id, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nama_menu))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(84, 84, 84))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBatalKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(263, 263, 263))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meja)
                    .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBatalKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(311, 311, 311))
        );

        jTabbedPane1.addTab("Entri Order", jPanel3);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Daftar Pesanan");

        tablePesanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablePesananMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tablePesanan);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Detail Pesanan");

        Nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama.setText("Nama :");

        Nama1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama1.setText("Meja :");

        Nama2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama2.setText("Daftar Menu :");

        btnKonfirmasiPesanan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKonfirmasiPesanan.setText("Konfirmasi");
        btnKonfirmasiPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiPesananActionPerformed(evt);
            }
        });

        detailNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        detailNama.setText("-");

        detailMeja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        detailMeja.setText("-");

        listDetailPesanan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Nama2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailNama, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKonfirmasiPesanan)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(detailMeja))
                                .addComponent(listDetailPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailNama))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailMeja))
                .addGap(32, 32, 32)
                .addComponent(Nama2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listDetailPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKonfirmasiPesanan)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pesanan", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMenuMouseClicked
        menu_id.setText(tableMenu.getValueAt(tableMenu.getSelectedRow(), 0).toString());
        nama_menu.setText(tableMenu.getValueAt(tableMenu.getSelectedRow(), 1).toString());
        harga.setText(tableMenu.getValueAt(tableMenu.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tableMenuMouseClicked

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void mejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mejaActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        nama.setText("");
        jumlah.setText("");
        nama_menu.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            st = cn.createStatement();
            if(Integer.parseInt(jumlah.getText()) >= Integer.parseInt(tableMenu.getValueAt(tableMenu.getSelectedRow(), 3).toString())) {
                JOptionPane.showMessageDialog(this, "Jumlah pesanan melebihi stok!!");
            } else {
                double hasil =  Double.parseDouble(harga.getText())  * Double.parseDouble(jumlah.getText());
                int total = (int) Math.round(hasil);
                
                int stokNew = Integer.parseInt(tableMenu.getValueAt(tableMenu.getSelectedRow(), 3).toString()) - Integer.parseInt(jumlah.getText());

                System.out.println(idTransaksi);

                st.executeUpdate("INSERT INTO pesanan(menu_id, transaksi_id, jumlah, total, created_at, updated_at) VALUES('"+ menu_id.getText() +"', '"+ idTransaksi +"', '"+ jumlah.getText() +"', '"+ total +"', '"+ now +"', '"+ now +"')");
                st.executeUpdate("UPDATE menu SET stok = '"+ stokNew +"' WHERE id = '"+ menu_id.getText() +"'");
                JOptionPane.showMessageDialog(this, "Menu berhasil ditambahkan");

                jumlah.setText("");
                tampilDataKeranjang();
                tampilData("");
            }

        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("INSERT INTO transaksi(nama, meja, total, created_at, updated_at) VALUES('"+ nama.getText() +"', '"+ meja.getSelectedItem() +"', 0, '"+ now +"', '"+ now +"')");
            st.executeUpdate("UPDATE meja SET status = 0  WHERE id = '"+ meja.getSelectedItem() +"'");
            rs = st.executeQuery("SELECT id FROM transaksi WHERE nama = '"+ nama.getText() +"'");
            while(rs.next()) {
                idTransaksi = rs.getString("id");
            };

            JOptionPane.showMessageDialog(this, "Pelanggan berhasil di daftarkan");
            nama.setEnabled(false);
            meja.setEnabled(false);
            btnDaftar.setEnabled(false);
            tampilData("");
            enabled();

        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM pesanan WHERE transaksi_id = '"+ idTransaksi +"'");

            int total = 0;
            while(rs.next()) {
                total += rs.getInt("total");
            };

            st.executeUpdate("UPDATE transaksi SET total = '"+ total +"' where id = '"+ idTransaksi +"'");

            JOptionPane.showMessageDialog(this, "Menu berhasil di order");
            resetAll();
            tampilData("");
            tampilDataMeja();
            tampilDataKeranjang();
            tampilDataPesanan("");

        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void btnBatalKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalKeranjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalKeranjangActionPerformed

    private void tablePesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesananMouseClicked
        detailNama.setText(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 1).toString());
        detailMeja.setText(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 2).toString());
        tampilDetailPesanan(tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 0).toString());
        idTransaksiPesanan = tablePesanan.getValueAt(tablePesanan.getSelectedRow(), 0).toString();
        btnKonfirmasiPesanan.setEnabled(true);
    }//GEN-LAST:event_tablePesananMouseClicked

    private void tablePesananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesananMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePesananMouseEntered

    private void btnKonfirmasiPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiPesananActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("UPDATE pesanan SET status = 'DIANTAR' where transaksi_id = '"+ idTransaksiPesanan +"'");

            JOptionPane.showMessageDialog(this ,"Pesanan berhasil dikonfirmasi!");
            tampilData("");
            tampilDataKeranjang();
            tampilDataPesanan("");

        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnKonfirmasiPesananActionPerformed

    public void judul() {
        Object[] judul = {
           "ID","Nama Menu", "Harga", "Stok",
        };
        tabModel = new DefaultTableModel(null, judul);
        tableMenu.setModel(tabModel);
    }
    
    public void judulPesanan() {
        Object[] judul = {
            "transaksi_id", "Nama", "Meja",
        };
        tabModelPesanan = new DefaultTableModel(null, judul);
        tablePesanan.setModel(tabModelPesanan);
    }
    
    public void judulKeranjang() {
        Object[] judul = {
            "ID" ,"Nama Menu", "Harga", "Jumlah"
        };
        tabModelKeranjang = new DefaultTableModel(null, judul);
        tableKeranjang.setModel(tabModelKeranjang);
    }
    
    public void tampilDataKeranjang() {
        try {
            st = cn.createStatement();
            tabModelKeranjang.getDataVector().removeAllElements();
            tabModelKeranjang.fireTableDataChanged();
            rs = st.executeQuery("SELECT pesanan.id, menu.nama_menu, menu.harga, pesanan.jumlah FROM pesanan INNER JOIN menu ON pesanan.menu_id = menu.id where pesanan.transaksi_id = '"+ idTransaksi +"'");

            while(rs.next()) {
                Object[] data = {
                    rs.getString("id"),
                    rs.getString("nama_menu"),
                    rs.getString("harga"),
                    rs.getString("jumlah"),
                };
                tabModelKeranjang.addRow(data);
            };

        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void tampilData(String where) {
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM menu " + where);

            while (rs.next()) {
                Object[] data = {
                    rs.getString("id"),
                    rs.getString("nama_menu"),
                    rs.getString("harga"),
                    rs.getString("stok"),
                };

                tabModel.addRow(data);
            }
//            tabModel.getDataVector().removeAllElements();
//            tabModel.fireTableDataChanged();
//            for(Menu menu: MainFrame.menuArrayList) {
//                tabModel.addRow(menu.parseToObject());
//            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void tampilDataPesanan(String where) {
        try {
            st = cn.createStatement();
            tabModelPesanan.getDataVector().removeAllElements();
            tabModelPesanan.fireTableDataChanged();
            rs = st.executeQuery("SELECT nama, meja, transaksi_id FROM transaksi INNER JOIN pesanan ON transaksi.id = pesanan.transaksi_id WHERE pesanan.status = 'DIBUAT' GROUP BY nama" + where);
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("transaksi_id"),
                    rs.getString("nama"),
                    rs.getString("meja"),
                };
                
                tabModelPesanan.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void tampilDetailPesanan(String id) {
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT pesanan.id, menu.nama_menu, menu.harga, pesanan.jumlah FROM pesanan INNER JOIN menu ON pesanan.menu_id = menu.id where pesanan.transaksi_id = '"+ id +"'");
            
            listDetailPesanan.removeAll();
            
            while(rs.next()) {
                listDetailPesanan.addItem(rs.getString("nama_menu") + "              " + "x" +rs.getString("jumlah"));
            };
            
            
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void tampilDataMeja() {
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM meja");
            meja.removeAllItems();
            while (rs.next()) {
                int status = Integer.parseInt(rs.getString("status"));
                if(status == 1) {
                    meja.addItem(rs.getString("id"));
                } 
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void enabled() {
        jumlah.setEnabled(true);
        
        tableMenu.setEnabled(true);
        tableKeranjang.setEnabled(true);
        btnBatal.setEnabled(true);
        btnTambah.setEnabled(true);
        btnKonfirmasi.setEnabled(true);
        btnBatalKeranjang.setEnabled(true);
    }
    
    public void resetAll() {
        idTransaksi = "0";
        
        jumlah.setEnabled(false);
        nama.setEnabled(true);
        meja.setEnabled(true);
        
        tableMenu.setEnabled(false);
        tableKeranjang.setEnabled(false);
        btnBatal.setEnabled(false);
        btnTambah.setEnabled(false);
        btnKonfirmasi.setEnabled(false);
        btnBatalKeranjang.setEnabled(false);
        btnDaftar.setEnabled(true);
        
        nama.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nama1;
    private javax.swing.JLabel Nama2;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalKeranjang;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JButton btnKonfirmasiPesanan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel detailMeja;
    private javax.swing.JLabel detailNama;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jumlah;
    private java.awt.List listDetailPesanan;
    private javax.swing.JComboBox<String> meja;
    private javax.swing.JTextField menu_id;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama_menu;
    private javax.swing.JLabel name;
    private javax.swing.JLabel roles;
    private javax.swing.JTable tableKeranjang;
    private javax.swing.JTable tableMenu;
    private javax.swing.JTable tablePesanan;
    // End of variables declaration//GEN-END:variables
}
