package Views;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class CashierPage extends JFrame {

    private JPanel panel;
    private JLabel TitlePageLabel;
    private JLabel TitleMenuLabel;
    private JTable ListPesananSelesai;
    private JList ListItemPembelian;
    private JTextField UangBayarTextField;
    private JButton prosesButton;
    private JButton konfirmasiButton;
    private JLabel UangLabel;
    private JLabel KembalianLabel;
    private JLabel NamaLabel;
    private JLabel TotalLabel;
    private JLabel ListMenuLabel;
    private JLabel DetailLabel;
    private JLabel MejaLabel;
    private JLabel IsiNamaLabel;
    private JLabel IsiMejaLabel;
    private JLabel IsiTotalLabel;
    private JLabel isiKembalianLabel;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public CashierPage() {

        ListPesananSelesai.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                String Nama = ListPesananSelesai.getValueAt(ListPesananSelesai.getSelectedRow(), 1).toString();
                String Meja = ListPesananSelesai.getValueAt(ListPesananSelesai.getSelectedRow(), 2).toString();
                String IdPesanan = ListPesananSelesai.getValueAt(ListPesananSelesai.getSelectedRow(), 3).toString();

                IsiNamaLabel.setText(Nama);
                IsiMejaLabel.setText(Meja);
            }
        });
    }

    public static void main(String[] args) {
        CashierPage c = new CashierPage();
        c.setContentPane(c.panel);
        c.setSize(500, 500);
        c.setVisible(true);
        c.setTitle("Tokyo Chinesse Food");
        c.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(11, 11, new Insets(0, 0, 0, 0), -1, -1));
        panel.setBackground(new Color(-3440950));
        panel.setForeground(new Color(-4473925));
        panel.setName("");
        TitlePageLabel = new JLabel();
        TitlePageLabel.setText("Tokyo Cashier");
        panel.add(TitlePageLabel, new GridConstraints(0, 0, 1, 11, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        TitleMenuLabel = new JLabel();
        TitleMenuLabel.setText("Menu Yang Selesai");
        panel.add(TitleMenuLabel, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(3, 2, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        UangLabel = new JLabel();
        UangLabel.setText("Uang Bayar :");
        panel.add(UangLabel, new GridConstraints(7, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        KembalianLabel = new JLabel();
        KembalianLabel.setText("Kembalian :");
        panel.add(KembalianLabel, new GridConstraints(8, 3, 1, 6, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        UangBayarTextField = new JTextField();
        UangBayarTextField.setText("");
        panel.add(UangBayarTextField, new GridConstraints(7, 4, 1, 7, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        prosesButton = new JButton();
        prosesButton.setText("Proses");
        panel.add(prosesButton, new GridConstraints(9, 5, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        DetailLabel = new JLabel();
        DetailLabel.setText("Detail Transaksi");
        panel.add(DetailLabel, new GridConstraints(1, 3, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        MejaLabel = new JLabel();
        MejaLabel.setText("Meja : ");
        panel.add(MejaLabel, new GridConstraints(3, 3, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ListMenuLabel = new JLabel();
        ListMenuLabel.setText("List Menu :");
        panel.add(ListMenuLabel, new GridConstraints(4, 3, 1, 8, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ListItemPembelian = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        ListItemPembelian.setModel(defaultListModel1);
        panel.add(ListItemPembelian, new GridConstraints(5, 3, 1, 8, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        TotalLabel = new JLabel();
        TotalLabel.setText("Total :");
        panel.add(TotalLabel, new GridConstraints(6, 3, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        konfirmasiButton = new JButton();
        konfirmasiButton.setText("Konfirmasi");
        panel.add(konfirmasiButton, new GridConstraints(10, 5, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        NamaLabel = new JLabel();
        NamaLabel.setText("Nama :");
        panel.add(NamaLabel, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ListPesananSelesai = new JTable();
        panel.add(ListPesananSelesai, new GridConstraints(2, 0, 9, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        isiKembalianLabel = new JLabel();
        isiKembalianLabel.setText("-");
        panel.add(isiKembalianLabel, new GridConstraints(8, 9, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        IsiTotalLabel = new JLabel();
        IsiTotalLabel.setText("-");
        panel.add(IsiTotalLabel, new GridConstraints(6, 9, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        IsiNamaLabel = new JLabel();
        IsiNamaLabel.setText("-");
        panel.add(IsiNamaLabel, new GridConstraints(2, 9, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        IsiMejaLabel = new JLabel();
        IsiMejaLabel.setText("-");
        panel.add(IsiMejaLabel, new GridConstraints(3, 9, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
