package Views;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LoginFrame extends JInternalFrame {
    private JButton loginButton;
    private JPanel panel;
    private JTextField usernameTextF;
    private JPasswordField passwordTextF;
    private JButton cancelButton;
    private JLabel passwordLabel;
    private JLabel usernameLabel;
    private JLabel loginTitle;

    public LoginFrame() {
        setSize(500, 500);
        this.add(panel);

        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String UserEmail = usernameTextF.getText();
                String UserPass = passwordTextF.getText();

                System.out.println("Your User Email is: " + UserEmail);
                System.out.println("Your Password is: " + UserPass);
            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

//    public static void main(String[] args) {
//        LoginPage l = new LoginPage();
//        l.setContentPane(l.panel);
//        l.setSize(500, 500);
//        l.setVisible(true);
//        l.setTitle("Tokyo Chinesse Food");
//        l.setDefaultCloseOperation(EXIT_ON_CLOSE);
//    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(4, 3, new Insets(100, 150, 100, 150), -1, -1));
        panel.setBackground(new Color(-3440950));
        usernameTextF = new JTextField();
        usernameTextF.setText("");
        panel.add(usernameTextF, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordTextF = new JPasswordField();
        passwordTextF.setColumns(3);
        passwordTextF.setText("");
        panel.add(passwordTextF, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), new Dimension(150, -1), 0, false));
        loginButton = new JButton();
        loginButton.setText("Login");
        loginButton.setVerticalAlignment(0);
        panel.add(loginButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelButton = new JButton();
        cancelButton.setHorizontalAlignment(0);
        cancelButton.setHorizontalTextPosition(11);
        cancelButton.setText("Cancel");
        cancelButton.setVerticalAlignment(0);
        cancelButton.setVerticalTextPosition(0);
        panel.add(cancelButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usernameLabel = new JLabel();
        usernameLabel.setText("Username");
        panel.add(usernameLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordLabel = new JLabel();
        passwordLabel.setText("Password");
        panel.add(passwordLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginTitle = new JLabel();
        loginTitle.setText("Login Page");
        panel.add(loginTitle, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_SOUTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
