/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRestoran.cashier;

import java.awt.print.PrinterException;
import javax.swing.table.DefaultTableModel;
import AplikasiRestoran.auth.User;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author idaba
 */
public class CashierPanel extends javax.swing.JInternalFrame {
    private Statement st;
    private ResultSet rs;
    private DefaultTableModel tabModel;
    private DefaultTableModel tabModelDetail;
    private DefaultTableModel tabModelHistory;
    private DefaultTableModel tabModelDetailHistory;
    private Connection cn = Koneksi.Koneksi.koneksiDB();

    private LocalDateTime now = LocalDateTime.now();
    
    private String idTransaksi;
    private String idHistory;
    /**
     * Creates new form CashierPanel
     */
    public CashierPanel(User user) {
        initComponents();
        name.setText(user.getName());
        roles.setText(user.getRoles());
        judul();
        judulDetail();
        tampilData();
        judulHistory();
        judulDetailHistory();
        tampilDataHistory();
        
       
        
        btnKonfirmasi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMeja = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JLabel();
        inputBayar = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        txtTotal1 = new javax.swing.JLabel();
        txtTotal2 = new javax.swing.JLabel();
        btnKonfirmasi = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDetailHistory = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        buktiTransaksi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHNama = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHMeja = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtHTotal = new javax.swing.JLabel();
        txtHKembalian = new javax.swing.JLabel();
        txtTotal4 = new javax.swing.JLabel();
        txtTotal5 = new javax.swing.JLabel();
        txtTotal6 = new javax.swing.JLabel();
        txtHBayar = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtWaktu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();
        btnKonfirmasi1 = new javax.swing.JButton();
        roles = new javax.swing.JLabel();

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setText("-");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tableTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Detail Transaksi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nama :");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNama.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Meja :");

        txtMeja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMeja.setText("-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("List Menu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Total :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Uang Bayar :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Kembalian :");

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTotal.setText("-");

        txtKembalian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtKembalian.setText("-");

        inputBayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnProses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        txtTotal1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal1.setText("Rp.");

        txtTotal2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal2.setText("Rp.");

        btnKonfirmasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKonfirmasi.setText("Konfirmasi");
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        tableDetailHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableDetailHistory);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtMeja)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNama)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTotal2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKembalian))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTotal1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal)))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(inputBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnProses)
                                .addGap(18, 18, 18)
                                .addComponent(btnKonfirmasi))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMeja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotal)
                    .addComponent(txtTotal1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKembalian)
                    .addComponent(txtTotal2))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(btnKonfirmasi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi Masuk", jPanel4);

        tableHistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHistoryMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableHistory);

        buktiTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Detail Transaksi");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nama :");

        txtHNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHNama.setText("-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Meja :");

        txtHMeja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHMeja.setText("-");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("List Menu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Total :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Uang Bayar :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Kembalian :");

        txtHTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHTotal.setText("-");

        txtHKembalian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHKembalian.setText("-");

        txtTotal4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal4.setText("Rp.");

        txtTotal5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal5.setText("Rp.");

        txtTotal6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal6.setText("Rp.");

        txtHBayar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHBayar.setText("-");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Waktu :");

        txtWaktu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtWaktu.setText("-");

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDetail);

        javax.swing.GroupLayout buktiTransaksiLayout = new javax.swing.GroupLayout(buktiTransaksi);
        buktiTransaksi.setLayout(buktiTransaksiLayout);
        buktiTransaksiLayout.setHorizontalGroup(
            buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buktiTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buktiTransaksiLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buktiTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHNama)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buktiTransaksiLayout.createSequentialGroup()
                        .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(buktiTransaksiLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtWaktu))
                            .addGroup(buktiTransaksiLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtHMeja))
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buktiTransaksiLayout.createSequentialGroup()
                                .addComponent(txtTotal5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHKembalian))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(buktiTransaksiLayout.createSequentialGroup()
                                    .addComponent(txtTotal6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHBayar))
                                .addGroup(buktiTransaksiLayout.createSequentialGroup()
                                    .addComponent(txtTotal4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHTotal))))
                        .addGap(24, 24, 24))))
        );
        buktiTransaksiLayout.setVerticalGroup(
            buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buktiTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtHNama))
                .addGap(20, 20, 20)
                .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtHMeja))
                .addGap(16, 16, 16)
                .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtWaktu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtHTotal)
                    .addComponent(txtTotal4))
                .addGap(18, 18, 18)
                .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtHBayar)
                    .addComponent(txtTotal6))
                .addGap(18, 18, 18)
                .addGroup(buktiTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtHKembalian)
                    .addComponent(txtTotal5))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        btnKonfirmasi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKonfirmasi1.setText("Cetak");
        btnKonfirmasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buktiTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKonfirmasi1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buktiTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnKonfirmasi1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("History Transaksi", jPanel3);

        roles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roles.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        txtNama.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 1).toString());
        txtMeja.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 2).toString());
        txtTotal.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 3).toString());
        idTransaksi = tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 0).toString();

        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT menu.nama_menu, menu.harga, pesanan.jumlah, pesanan.total from pesanan INNER JOIN menu ON pesanan.menu_id = menu.id WHERE pesanan.transaksi_id = '"+ idTransaksi +"'");
            tabModelDetailHistory.getDataVector().removeAllElements();
            tabModelDetailHistory.fireTableDataChanged();
            while(rs.next()) {
                Object[] data = {
                    rs.getString("nama_menu"),
                    "Rp."+rs.getString("harga"),
                    "x"+rs.getString("jumlah"),
                    "Rp."+rs.getString("total"),
                };
                
                tabModelDetailHistory.addRow(data);
            }

        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        int total = Integer.parseInt(txtTotal.getText());
        int bayar = Integer.parseInt(inputBayar.getText());

        if(bayar >= total) {
            int hasil = total - bayar;

            StringBuilder sb = new StringBuilder(Integer.toString(hasil));
            if(sb.length() > 1) {
                sb.deleteCharAt(0);
            }

            txtKembalian.setText(sb.toString());

            btnKonfirmasi.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Duit pembayaran kurang!!");
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("UPDATE transaksi SET status = 'LUNAS', bayar = '"+ inputBayar.getText() +"', updated_at = '"+ now +"' where id = '"+ idTransaksi +"'");
            st.executeUpdate("UPDATE meja SET status = 1 where id='"+ txtMeja.getText() +"'");
            JOptionPane.showMessageDialog(this, "Transaksi berhasil!!");
            txtNama.setText("");
            txtMeja.setText("");
            txtTotal.setText("");
            idTransaksi = "0";
            tabModelDetailHistory.getDataVector().removeAllElements();
            tabModelDetailHistory.fireTableDataChanged();
            tampilData();
            tampilDataHistory();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void tableHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHistoryMouseClicked
        //        txtHNama.setText(tableHistory.getValueAt(tableHistory.getSelectedRow(), 1).toString());
        //        txtHMeja.setText(tableHistory.getValueAt(tableHistory.getSelectedRow(), 2).toString());
        //        txtTotal.setText(tableHistory.getValueAt(tableHistory.getSelectedRow(), 3).toString());
        idHistory = tableHistory.getValueAt(tableHistory.getSelectedRow(), 0).toString();

        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT menu.nama_menu, menu.harga, pesanan.jumlah, pesanan.total from pesanan INNER JOIN menu ON pesanan.menu_id = menu.id WHERE pesanan.transaksi_id = '"+ idHistory +"'");
            tabModelDetail.getDataVector().removeAllElements();
            tabModelDetail.fireTableDataChanged();
            while(rs.next()) {
                Object[] data = {
                    rs.getString("nama_menu"),
                    "Rp."+rs.getString("harga"),
                    "x"+rs.getString("jumlah"),
                    "Rp."+rs.getString("total"),
                };
                
                tabModelDetail.addRow(data);
            }

            rs = st.executeQuery("SELECT * FROM transaksi WHERE id = '"+ idHistory +"'");
            while(rs.next()) {
                int total = Integer.parseInt(rs.getString("total"));
                int bayar = Integer.parseInt(rs.getString("bayar"));
                int hasil = total - bayar;
                StringBuilder sb = new StringBuilder(Integer.toString(hasil));
                if(sb.length() > 1) {
                    sb.deleteCharAt(0);
                }

                txtHNama.setText(rs.getString("nama"));
                txtHMeja.setText(rs.getString("meja"));
                txtWaktu.setText(rs.getString("updated_at"));
                txtHTotal.setText(rs.getString("total"));
                txtHBayar.setText(rs.getString("bayar"));
                txtHKembalian.setText(sb.toString());
            }

        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableHistoryMouseClicked

    private void btnKonfirmasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasi1ActionPerformed
//        MessageFormat judul = new MessageFormat("PENJUALAN");
//        MessageFormat footer = new MessageFormat("page(0,number,integer)");
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        
        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) {
; //To change body of generated methods, choose Tools | Templates.
                pageFormat.setOrientation(PageFormat.LANDSCAPE);
                
                if(pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 =  (Graphics2D)graphics;
                g2.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                g2.scale(1, 1);
                
                buktiTransaksi.print(g2);
                
                return Printable.PAGE_EXISTS;
            }
            
        });
        
         boolean ok = job.printDialog();
            if(ok) {
                
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(CashierPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            }
    
    }//GEN-LAST:event_btnKonfirmasi1ActionPerformed

    public void judul() {
        Object[] judul = {
           "ID","Nama", "Meja", "Total", "Status"
        };
        tabModel = new DefaultTableModel(null, judul);
        tableTransaksi.setModel(tabModel);
    }
    
    public void judulDetail() {
        Object[] judul = {
           "Nama Menu", "Harga", "Jumlah", "Total"
        };
        tabModelDetail = new DefaultTableModel(null, judul);
        tableDetail.setModel(tabModelDetail);
    }
    
    public void judulHistory() {
        Object[] judul = {
           "ID","Nama", "Waktu Transaksi", "Status"
        };
        tabModelHistory = new DefaultTableModel(null, judul);
        tableHistory.setModel(tabModelHistory);
    }
    
    public void judulDetailHistory() {
        Object[] judul = {
           "Nama Menu", "Harga", "Jumlah", "Total"
        };
        tabModelDetailHistory = new DefaultTableModel(null, judul);
        tableDetailHistory.setModel(tabModelDetailHistory);
    }
    
    public void tampilData() {
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM transaksi WHERE status = 'TERTUNDA' ORDER BY id DESC");
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("id"),
                    rs.getString("nama"),
                    rs.getString("meja"),
                    rs.getString("total"),
                    rs.getString("status"),
                };
                
                tabModel.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void tampilDataHistory() {
        try {
            st = cn.createStatement();
            tabModelHistory.getDataVector().removeAllElements();
            tabModelHistory.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM transaksi WHERE status = 'LUNAS' ORDER BY updated_at DESC");
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("id"),
                    rs.getString("nama"),
                    rs.getString("updated_at"),
                    rs.getString("status"),
                };
                
                tabModelHistory.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JButton btnKonfirmasi1;
    private javax.swing.JButton btnProses;
    private javax.swing.JPanel buktiTransaksi;
    private javax.swing.JTextField inputBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel roles;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTable tableDetailHistory;
    private javax.swing.JTable tableHistory;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JLabel txtHBayar;
    private javax.swing.JLabel txtHKembalian;
    private javax.swing.JLabel txtHMeja;
    private javax.swing.JLabel txtHNama;
    private javax.swing.JLabel txtHTotal;
    private javax.swing.JLabel txtKembalian;
    private javax.swing.JLabel txtMeja;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtTotal1;
    private javax.swing.JLabel txtTotal2;
    private javax.swing.JLabel txtTotal4;
    private javax.swing.JLabel txtTotal5;
    private javax.swing.JLabel txtTotal6;
    private javax.swing.JLabel txtWaktu;
    // End of variables declaration//GEN-END:variables
}
