/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRestoran.admin;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import AplikasiRestoran.auth.User;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
/**
 *
 * @author Admin
 */
public class AdminPanel extends javax.swing.JInternalFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    public DefaultTableModel tabModelUser;
    public DefaultTableModel tabModelMeja;
    Connection cn = Koneksi.Koneksi.koneksiDB();
    
//    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
    LocalDateTime now = LocalDateTime.now();
    /**
     * Creates new form AdminPanel
     */
    
    static String sha1(String input) throws NoSuchAlgorithmException {
        MessageDigest mDigest = MessageDigest.getInstance("SHA1");
        byte[] result = mDigest.digest(input.getBytes());
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < result.length; i++) {
            sb.append(Integer.toString((result[i] & 0xff) + 0x100, 16).substring(1));
        }         
        return sb.toString();
    }
    
    public AdminPanel(User user) {
        initComponents();
        name.setText(user.getName());
        roles.setText(user.getRoles());
        
        judulMenu();
        tampilDataMenu("");
        txtIdMenu.setEnabled(false);
        btnEditMenu.setEnabled(false);
        btnHapusMenu.setEnabled(false);
        btnBatalMenu.setEnabled(false);
        
        judulUser();
        tampilDataUser("");
        txtIdUser.setEnabled(false);
        btnEditUser.setEnabled(false);
        btnHapusUser.setEnabled(false);
        btnBatalUser.setEnabled(false);
        btnTambahUser.setEnabled(true);
        
        judulMeja();
        tampilDataMeja("");
        btnEditMeja.setEnabled(false);
        btnBatalUser.setEnabled(false);
        txtIdMeja.setEnabled(false);
        txtStatusMeja.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roles = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdMenu = new javax.swing.JTextField();
        txtHargaMenu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStokMenu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEditMenu = new javax.swing.JButton();
        btnBatalMenu = new javax.swing.JButton();
        btnHapusMenu = new javax.swing.JButton();
        btnTambahMenu = new javax.swing.JButton();
        txtNamaMenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEditMeja = new javax.swing.JButton();
        btnBatalMeja = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMeja = new javax.swing.JTable();
        btnTambahMeja = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIdMeja = new javax.swing.JTextField();
        txtStatusMeja = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtEmailUser = new javax.swing.JTextField();
        btnTambahUser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNamaUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEditUser = new javax.swing.JButton();
        btnBatalUser = new javax.swing.JButton();
        btnHapusUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtIdUser = new javax.swing.JTextField();
        txtPasswordUser = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtLevelUser = new javax.swing.JComboBox<>();

        roles.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roles.setText("-");

        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setText("-");

        tableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMenu);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id");

        txtIdMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtHargaMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Harga");

        txtStokMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Stok");

        btnEditMenu.setText("Edit");
        btnEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMenuActionPerformed(evt);
            }
        });

        btnBatalMenu.setText("Batal");
        btnBatalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalMenuActionPerformed(evt);
            }
        });

        btnHapusMenu.setText("Hapus");
        btnHapusMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMenuActionPerformed(evt);
            }
        });

        btnTambahMenu.setText("Tambah");
        btnTambahMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMenuActionPerformed(evt);
            }
        });

        txtNamaMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtIdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBatalMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusMenu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStokMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahMenu))
                        .addGap(12, 12, 12)
                        .addComponent(btnEditMenu))
                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStokMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBatalMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapusMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu", jPanel1);

        btnEditMeja.setText("Edit");
        btnEditMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMejaActionPerformed(evt);
            }
        });

        btnBatalMeja.setText("Batal");
        btnBatalMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalMejaActionPerformed(evt);
            }
        });

        tableMeja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMeja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMejaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableMeja);

        btnTambahMeja.setText("Tambah");
        btnTambahMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMejaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("No Meja");

        txtIdMeja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtStatusMeja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(txtIdMeja)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnTambahMeja)
                        .addGap(12, 12, 12)
                        .addComponent(btnEditMeja))
                    .addComponent(txtStatusMeja)
                    .addComponent(jLabel12)
                    .addComponent(btnBatalMeja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatusMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatalMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Meja", jPanel3);

        txtEmailUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailUserActionPerformed(evt);
            }
        });

        btnTambahUser.setText("Tambah");
        btnTambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahUserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        txtNamaUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Password");

        btnEditUser.setText("Edit");
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnBatalUser.setText("Batal");
        btnBatalUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalUserActionPerformed(evt);
            }
        });

        btnHapusUser.setText("Hapus");
        btnHapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusUserActionPerformed(evt);
            }
        });

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableUser);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Id");

        txtIdUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Level");

        txtLevelUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "WAITER", "CASHIER", "OWNER" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(txtIdUser)
                    .addComponent(txtEmailUser)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnBatalUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusUser))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTambahUser)
                        .addGap(12, 12, 12)
                        .addComponent(btnEditUser))
                    .addComponent(txtNamaUser)
                    .addComponent(jLabel6)
                    .addComponent(txtPasswordUser)
                    .addComponent(jLabel9)
                    .addComponent(txtLevelUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLevelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBatalUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMenuMouseClicked
        txtIdMenu.setText(tableMenu.getValueAt(tableMenu.getSelectedRow(), 0).toString());
        txtNamaMenu.setText(tableMenu.getValueAt(tableMenu.getSelectedRow(), 1).toString());
        txtHargaMenu.setText(tableMenu.getValueAt(tableMenu.getSelectedRow(), 2).toString());
        txtStokMenu.setText(tableMenu.getValueAt(tableMenu.getSelectedRow(), 3).toString());

        btnEditMenu.setEnabled(true);
        btnHapusMenu.setEnabled(true);
        btnBatalMenu.setEnabled(true);
        btnTambahMenu.setEnabled(false);
    }//GEN-LAST:event_tableMenuMouseClicked

    private void btnEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMenuActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("UPDATE menu SET nama_menu = '"+ txtNamaMenu.getText() +"', harga = '"+ txtHargaMenu.getText() +"', stok = '"+ txtStokMenu.getText() +"', updated_at = '"+ now +"' WHERE id = '"+ txtIdMenu.getText() +"'");
            JOptionPane.showMessageDialog(this, "Menu Berhasil di Update!!");
            tampilDataMenu("");
            resetMenu();

        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditMenuActionPerformed

    private void btnBatalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalMenuActionPerformed
        resetMenu();
    }//GEN-LAST:event_btnBatalMenuActionPerformed

    private void btnHapusMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMenuActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("DELETE FROM menu WHERE id = '"+ txtIdMenu.getText() +"'");
            JOptionPane.showMessageDialog(this, "Menu Berhasil di Hapus!!");
            tampilDataMenu("");
            resetMenu();

        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusMenuActionPerformed

    private void btnTambahMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMenuActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("INSERT INTO menu(stok, nama_menu, harga, created_at, updated_at) VALUES('"+ txtStokMenu.getText() +"', '"+ txtNamaMenu.getText() +"', '"+ txtHargaMenu.getText() +"', '"+ now +"', '"+ now +"')");
            JOptionPane.showMessageDialog(this, "Menu berhasil di tambahkan!!");
            tampilDataMenu("");
            resetMenu();
        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahMenuActionPerformed

    private void btnEditMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMejaActionPerformed
        try {
            st = cn.createStatement();
            if(txtStatusMeja.getText().equals("DITEMPATI")) {
                st.executeUpdate("UPDATE meja SET status = 1 ,updated_at = '"+ now +"' WHERE id = '"+ txtIdMeja.getText() +"'");
            } else if(txtStatusMeja.getText().equals("KOSONG")) {
                st.executeUpdate("UPDATE meja SET status = 0 ,updated_at = '"+ now +"' WHERE id = '"+ txtIdMeja.getText() +"'");;
            }
            JOptionPane.showMessageDialog(this, "Meja Berhasil di Update!!");

            tampilDataMeja("");
            resetMeja();

        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditMejaActionPerformed

    private void btnBatalMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalMejaActionPerformed
        resetMeja();
    }//GEN-LAST:event_btnBatalMejaActionPerformed

    private void tableMejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMejaMouseClicked
        txtIdMeja.setText(tableMeja.getValueAt(tableMeja.getSelectedRow(), 0).toString());
        txtStatusMeja.setText(tableMeja.getValueAt(tableMeja.getSelectedRow(), 1).toString());

        btnEditMeja.setEnabled(true);
        btnBatalMeja.setEnabled(true);
        btnTambahMeja.setEnabled(false);
    }//GEN-LAST:event_tableMejaMouseClicked

    private void btnTambahMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMejaActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("INSERT INTO meja(created_at, updated_at) VALUES('"+ now +"', '"+ now +"')");
            JOptionPane.showMessageDialog(this, "Meja berhasil di tambahkan!!");
            tampilDataMeja("");
            resetMeja();
        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahMejaActionPerformed

    private void txtEmailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailUserActionPerformed

    private void btnTambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahUserActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("INSERT INTO users(name, email, password, level, created_at, updated_at) VALUES('"+ txtNamaUser.getText() +"', '"+ txtEmailUser.getText() +"', '"+ sha1(txtPasswordUser.getText()) +"', '"+ txtLevelUser.getSelectedItem() +"', '"+ now +"', '"+ now +"')");
            JOptionPane.showMessageDialog(this, "User berhasil di tambahkan!!");
            tampilDataUser("");
            resetUser();
        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        try {
            st = cn.createStatement();
            if(txtPasswordUser.getText() == "") {
                st.executeUpdate("UPDATE users SET name = '"+ txtNamaUser.getText() +"', email = '"+ txtEmailUser.getText() +"', level = '"+ txtLevelUser.getSelectedItem() +"',updated_at = '"+ now +"' WHERE id = '"+ txtIdUser.getText() +"'");
            } else {
                st.executeUpdate("UPDATE users SET name = '"+ txtNamaUser.getText() +"', email = '"+ txtEmailUser.getText() +"', password = '"+ sha1(txtPasswordUser.getText()) +"', level = '"+ txtLevelUser.getSelectedItem() +"',updated_at = '"+ now +"' WHERE id = '"+ txtIdUser.getText() +"'");
            }
            JOptionPane.showMessageDialog(this, "User Berhasil di Update!!");

            tampilDataUser("");
            resetUser();

        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnBatalUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalUserActionPerformed
        resetUser();
    }//GEN-LAST:event_btnBatalUserActionPerformed

    private void btnHapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusUserActionPerformed
        try {
            st = cn.createStatement();
            st.executeUpdate("DELETE FROM users WHERE id = '"+ txtIdUser.getText() +"'");
            JOptionPane.showMessageDialog(this, "Menu Berhasil di Hapus!!");
            tampilDataUser("");
            resetUser();

        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusUserActionPerformed

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
        txtIdUser.setText(tableUser.getValueAt(tableUser.getSelectedRow(), 0).toString());
        txtNamaUser.setText(tableUser.getValueAt(tableUser.getSelectedRow(), 1).toString());
        txtEmailUser.setText(tableUser.getValueAt(tableUser.getSelectedRow(), 2).toString());
        txtLevelUser.setSelectedItem(tableUser.getValueAt(tableUser.getSelectedRow(), 3).toString());

        btnEditUser.setEnabled(true);
        btnHapusUser.setEnabled(true);
        btnBatalUser.setEnabled(true);
        btnTambahUser.setEnabled(false);
    }//GEN-LAST:event_tableUserMouseClicked

    public void resetMenu()
    {
        txtIdMenu.setText("");
        txtNamaMenu.setText("");
        txtHargaMenu.setText("");
        txtStokMenu.setText("");

        btnEditMenu.setEnabled(false);
        btnHapusMenu.setEnabled(false);
        btnBatalMenu.setEnabled(false);
        btnTambahMenu.setEnabled(true);
    }
    public void resetUser()
    {
        txtIdUser.setText("");
        txtNamaUser.setText("");
        txtEmailUser.setText("");
        txtPasswordUser.setText("");
        txtLevelUser.setSelectedIndex(0);

        btnEditUser.setEnabled(false);
        btnHapusUser.setEnabled(false);
        btnBatalUser.setEnabled(false);
        btnTambahUser.setEnabled(true);
    }
    
    
    public void resetMeja()
    {
        txtIdMeja.setText("");
        txtStatusMeja.setText("");

        btnEditMeja.setEnabled(false);
        btnBatalMeja.setEnabled(false);
        btnTambahMeja.setEnabled(true);
    }
    
    public void judulMenu() {
        Object[] judul = {
           "ID","Nama Menu", "Harga", "Stok"
        };
        tabModel = new DefaultTableModel(null, judul);
        tableMenu.setModel(tabModel);
    }
    
    public void tampilDataMenu(String where) {
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM menu " + where);
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("id"),
                    rs.getString("nama_menu"),
                    rs.getString("harga"),
                    rs.getString("stok")
                };
                
                tabModel.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void judulUser() {
        Object[] judul = {
           "ID","Nama", "Email", "Level"
        };
        tabModelUser = new DefaultTableModel(null, judul);
        tableUser.setModel(tabModelUser);
    }
    
    public void tampilDataUser(String where) {
        try {
            st = cn.createStatement();
            tabModelUser.getDataVector().removeAllElements();
            tabModelUser.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM users " + where);
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getString("email"),
                    rs.getString("level")
                };
                
                tabModelUser.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void judulMeja() {
        Object[] judul = {
           "No Meja","Status",
        };
        tabModelMeja = new DefaultTableModel(null, judul);
        tableMeja.setModel(tabModelMeja);
    }
    
    public void tampilDataMeja(String where) {
        try {
            st = cn.createStatement();
            tabModelMeja.getDataVector().removeAllElements();
            tabModelMeja.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM  meja " + where);
            
            while (rs.next()) {
                String status = "";
                if(Integer.parseInt(rs.getString("status")) == 0) {
                    status = "DITEMPATI";
                } else if(Integer.parseInt(rs.getString("status")) == 1) {
                    status = "KOSONG";  
                 }
                Object[] data = {
                    rs.getString("id"),
                    status
                };
                
                tabModelMeja.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalMeja;
    private javax.swing.JButton btnBatalMenu;
    private javax.swing.JButton btnBatalUser;
    private javax.swing.JButton btnEditMeja;
    private javax.swing.JButton btnEditMenu;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnHapusMenu;
    private javax.swing.JButton btnHapusUser;
    private javax.swing.JButton btnTambahMeja;
    private javax.swing.JButton btnTambahMenu;
    private javax.swing.JButton btnTambahUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel roles;
    private javax.swing.JTable tableMeja;
    private javax.swing.JTable tableMenu;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtHargaMenu;
    private javax.swing.JTextField txtIdMeja;
    private javax.swing.JTextField txtIdMenu;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JComboBox<String> txtLevelUser;
    private javax.swing.JTextField txtNamaMenu;
    private javax.swing.JTextField txtNamaUser;
    private javax.swing.JPasswordField txtPasswordUser;
    private javax.swing.JTextField txtStatusMeja;
    private javax.swing.JTextField txtStokMenu;
    // End of variables declaration//GEN-END:variables
}
